###############################################################################
# Copyright (c) 2022, 2023 SWTChart project
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Matthias Mailänder - initial API and implementation
###############################################################################

name: Continuous Integration
on:
    push:
        branches:    
            - master
            - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SWTChart
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Build with Maven
      uses: coactions/setup-xvfb@v1
      with:
        run: mvn -f org.eclipse.swtchart.cbi/pom.xml -T 1C clean package --batch-mode --no-transfer-progress

    - name: Deploy update-site to the repository Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./org.eclipse.swtchart.updatesite/target/repository